name: _offline
timestamp: 1650511344
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _offline
  timestamp: 1650508408
positions:
  top-a: 'Top A'
  breadcrumbs: Hero
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  hero: Hero
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  below: Below
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-8907: 'System Messages'
  content:
    system-content-2965: 'Page Content'
  position:
    position-position-6504: 'Top A'
    position-position-5604: Hero
  jlnavbar:
    jlnavbar-3322: 'JL Navbar'
  jlfooterinfo:
    jlfooterinfo-6319: 'JL Footer Info'
  social:
    social-9980: Social
  copyright:
    copyright-3651: Copyright
inherit:
  default:
    top: top
    navigation: navigation
    hero: hero
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    position-position-6504: position-position-9039
    jlnavbar-3322: jlnavbar-2718
    position-position-5604: position-position-5320
    jlfooterinfo-6319: jlfooterinfo-6138
    social-9980: social-3367
    copyright-3651: copyright-6042
