<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_tags
 *
 * @copyright   (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Tags\Site\Helper\RouteHelper;

// includes placehold
$yt_temp = Factory::getApplication()->getTemplate();
include (JPATH_BASE . '/templates/'.$yt_temp.'/includes/placehold.php');

// Begin: dev added
global $leadingFlag;
$doc = Factory::getDocument();
$app = Factory::getApplication();
$templateParams = Factory::getApplication()->getTemplate(true)->params;
// End: dev added

/** @var Joomla\CMS\WebAsset\WebAssetManager $wa */
$wa = $this->document->getWebAssetManager();
$wa->useScript('com_tags.tag-default');

// Get the user object.
$user = Factory::getUser();

// Check if user is allowed to add/edit based on tags permissions.
// Do we really have to make it so people can see unpublished tags???
$canEdit      = $user->authorise('core.edit', 'com_tags');
$canCreate    = $user->authorise('core.create', 'com_tags');
$canEditState = $user->authorise('core.edit.state', 'com_tags');
?>
<div class="com-tags__items">
	<form action="<?php echo htmlspecialchars(Uri::getInstance()->toString()); ?>" method="post" name="adminForm" id="adminForm">
		<?php if ($this->params->get('filter_field') || $this->params->get('show_pagination_limit')) : ?>
			<?php if ($this->params->get('filter_field')) : ?>
				<div class="com-tags-tags__filter btn-group">
					<label class="filter-search-lbl visually-hidden" for="filter-search">
						<?php echo Text::_('COM_TAGS_TITLE_FILTER_LABEL'); ?>
					</label>
					<input
						type="text"
						name="filter-search"
						id="filter-search"
						value="<?php echo $this->escape($this->state->get('list.filter')); ?>"
						class="inputbox" onchange="document.adminForm.submit();"
						placeholder="<?php echo Text::_('COM_TAGS_TITLE_FILTER_LABEL'); ?>"
					>
					<button type="submit" name="filter_submit" class="btn btn-primary"><?php echo Text::_('JGLOBAL_FILTER_BUTTON'); ?></button>
					<button type="reset" name="filter-clear-button" class="btn btn-secondary"><?php echo Text::_('JSEARCH_FILTER_CLEAR'); ?></button>
				</div>
			<?php endif; ?>
			<?php if ($this->params->get('show_pagination_limit')) : ?>
				<div class="btn-group float-end">
					<label for="limit" class="visually-hidden">
						<?php echo Text::_('JGLOBAL_DISPLAY_NUM'); ?>
					</label>
					<?php echo $this->pagination->getLimitBox(); ?>
				</div>
			<?php endif; ?>

			<input type="hidden" name="limitstart" value="">
			<input type="hidden" name="task" value="">
		<?php endif; ?>
	</form>

	<?php if (empty($this->items)) : ?>
		<div class="alert alert-info">
			<span class="icon-info-circle" aria-hidden="true"></span><span class="visually-hidden"><?php echo Text::_('INFO'); ?></span>
			<?php echo Text::_('COM_TAGS_NO_ITEMS'); ?>
		</div>
	<?php else : ?>
		<ul class="com-tags-tag__category blank list_tags">
			<?php foreach ($this->items as $i => $item) : ?>
				<?php if ($item->core_state == 0) : ?>
					<li class="item list-group-item-danger">
				<?php else : ?>
					<li class="item items-row">
				<?php endif; ?>
					<div class="item">
						<div class="article-text">
							<div class="page-header">
								<?php if (($item->type_alias === 'com_users.category') || ($item->type_alias === 'com_banners.category')) : ?>
									<h2>
										<?php echo $this->escape($item->core_title); ?>
									</h2>
								<?php else : ?>
									<h2>
										<a href="<?php echo Route::_($item->link); ?>">
											<?php echo $this->escape($item->core_title); ?>
										</a>
									</h2>
								<?php endif; ?>
							</div>
							<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
							<?php echo $item->event->afterDisplayTitle; ?>
							
							<?php $images  = json_decode($item->core_images); ?>
							<?php if ($this->params->get('tag_list_show_item_image', 1) == 1 && !empty($images->image_intro)) : ?>
							
								<?php
									$imgfloat = (empty($images->float_intro)) ?  'left' :$images->float_intro; 
									$imgW = (isset($leadingFlag) && $leadingFlag)?$templateParams->get('leading_width', '300'):$templateParams->get('intro_width', '200');
									$imgH = (isset($leadingFlag) && $leadingFlag)?$templateParams->get('leading_height', '300'):$templateParams->get('intro_height', '200');
									$imgsrc = YTTemplateUtils::resize($images->image_intro, $imgW, $imgH, array($templateParams->get('thumbnail_background', '#ffffff')));
									
									//Create placeholder items images
									$src = $images->image_intro;
									if (file_exists(JPATH_BASE . '/' . $src)) {								
										$thumb_img = '<img src="'.$imgsrc.'"'.@$imgattr.' alt="'.$images->image_intro_alt.'" />';
										$full_img =  JURI::base().'/'.htmlspecialchars($images->image_intro);
									} else if ($is_placehold) {					
										$thumb_img = yt_placehold($placehold_size['listing']);
										$full_img  = 'http://placehold.it/'.$placehold_size['article'].'/969696';
									}
									
									$imgattr ='';
									if($templateParams->get('includeLazyload')==1){
										$imgattr = ' data-original="'.$imgsrc.'"';
										$imgsrc  = JURI::base().'templates/'.JFactory::getApplication()->getTemplate().'/images/white.gif';
									}
								?>
								<div class="pull-<?php echo htmlspecialchars($imgfloat); ?> item-image">
									<a href="<?php echo Route::_(RouteHelper::getItemRoute($item->content_item_id, $item->core_alias, $item->core_catid, $item->core_language, $item->type_alias, $item->router)); ?>">
										<img src="<?php echo $imgsrc;//echo htmlspecialchars($images->image_intro); ?>" <?php echo $imgattr; ?>
											alt="<?php echo htmlspecialchars($images->image_intro_alt); ?>">
									</a>
									<div class="image-overlay">
										<div class="hover-links clearfix">
											<a class="hover-zoom" rel="prettyPhoto" title="<?php echo $images->image_intro_caption;?>"  href="<?php echo htmlspecialchars($images->image_fulltext); ?>"><i class="icon-external-link"></i></a>
											<a class="hover-link" href="<?php echo Route::_(RouteHelper::getItemRoute($item->content_item_id, $item->core_alias, $item->core_catid, $item->core_language, $item->type_alias, $item->router)); ?>"><i class="icon-plus"></i></a>
										</div>
									</div>
								</div>
							<?php endif; ?>
							
							<div class="item-headinfo">
								<dl class="article-info muted">
									<dt></dt>
									<dd>
										<div class="modified">
										<?php echo JText::sprintf( JHTML::_('date',$item->tag_date, 'DATE_FORMAT_LC2')); ?>
										</div>
									</dd>
								</dl>
							</div>
						
							<?php if ($this->params->get('tag_list_show_item_description', 1)) : ?>
								<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
								<?php echo $item->event->beforeDisplayContent; ?>
								<span class="tag-body">
									<?php echo HTMLHelper::_('string.truncate', $item->core_body, $this->params->get('tag_list_item_maximum_characters')); ?>
								</span>
								<div class="item-readmore">
									<a href="<?php echo Route::_($item->link); ?>" class="readmore"> 
										<?php echo JText::_('READ MORE'); ?> <i class="more-open"></i>	
									</a>
								</div>
								<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
								<?php echo $item->event->afterDisplayContent; ?>
							<?php endif; ?>
						</div>
					</div>
				</li>
			<?php endforeach; ?>
		</ul>
	<?php endif; ?>
</div>
