name: 15
timestamp: 1650511344
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1650508408
positions:
  top-a: 'Top A'
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  hero: Hero
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  below: Below
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-7040: 'Top A'
  jlnavbar:
    jlnavbar-9051: 'JL Navbar'
  jlfooterinfo:
    jlfooterinfo-6394: 'JL Footer Info'
  social:
    social-2140: Social
  copyright:
    copyright-1752: Copyright
inherit:
  default:
    top: top
    navigation: navigation
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    position-position-7040: position-position-9039
    jlnavbar-9051: jlnavbar-2718
    jlfooterinfo-6394: jlfooterinfo-6138
    social-2140: social-3367
    copyright-1752: copyright-6042
